import { QUEUES } from "../config/rabbitmq";

export const QUEUE_RETRY_LIMITS: Record<string, number> = {
  [QUEUES.ACBU_ESCROW_EVENTS]: 5,
  [QUEUES.ACBU_LENDING_POOL_EVENTS]: 5,
  [QUEUES.ACBU_SAVINGS_VAULT_EVENTS]: 5,
  [QUEUES.AUDIT_LOGS]: 3,
  [QUEUES.NOTIFICATIONS]: 5,
  [QUEUES.OTP_SEND]: 5,
  [QUEUES.REBALANCING]: 5,
  [QUEUES.STELLAR_EVENT_FAILURES]: 5,
  [QUEUES.USDC_CONVERSION]: 5,
  [QUEUES.USDC_CONVERT_AND_MINT]: 5,
  [QUEUES.WEBHOOKS]: 5,
  [QUEUES.WITHDRAWAL_PROCESSING]: 5,
  [QUEUES.XLM_TO_ACBU]: 5,
};

export const DEFAULT_MAX_RETRIES = 5;

export function getQueueMaxRetries(queueName: string): number {
  return QUEUE_RETRY_LIMITS[queueName] ?? DEFAULT_MAX_RETRIES;
}
